spring:
  application:
    name: Card Cost API

resilience4j.circuitbreaker:
  instances:
    binList:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
#      recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate

resilience4j.retry:
  instances:
    binList:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
#      ignoreExceptions:
#        - io.github.robwin.exception.BusinessException

springdoc.show-actuator: true
# swagger-ui custom path
springdoc.swagger-ui:
  path: /swagger-ui.html
# /api-docs endpoint custom path
springdoc.api-docs:
  path: /api-docs
logging.level:
  root: TRACE