spring:
  application:
    name: Card Cost API
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:cardCost
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform=org.hibernate.dialect.H2Dialect

resilience4j.circuitbreaker:
  instances:
    binList:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

resilience4j.retry:
  instances:
    binList:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2

springdoc.show-actuator: true

# swagger-ui custom path
springdoc.swagger-ui:
  path: /swagger-ui.html

# /api-docs endpoint custom path
springdoc.api-docs:
  path: /api-docs
#logging.level:
#  root: TRACE
hazelcast:
  spring:
    cache:
      prop:
        defaultReadTimeout: 1