CREATE TABLE CLEARING_COST (
    country VARCHAR(64) PRIMARY KEY,
    cost DOUBLE
);
CREATE TABLE USERS (
    username VARCHAR(255) PRIMARY KEY,
    password VARCHAR(500),
    role VARCHAR(255)
);